server/ttdashboard/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template
from django.contrib import admin
from settings import *
admin.autodiscover()

urlpatterns = patterns('',
   (r'^js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '%s/templates/js/' % PROJECT_ROOT}),
   (r'^css/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '%s/templates/css/' % PROJECT_ROOT}),
   (r'^img/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '%s/templates/img/' % PROJECT_ROOT}),
   (r'^tmp/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '%s/templates/tmp/' % PROJECT_ROOT}),

   url(r'^api/', include('api.urls')),

   url(r'^criss/', include('website.urls')),
   #url(r'^', direct_to_template, {'template': 'manage.html'}),
   url(r'^', include('website.urls')),
   url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
   url(r'^admin/', include(admin.site.urls)),
)

server/ttdashboard/website/forms.py
from django import forms

class LoginForm(forms.Form):
   username = forms.CharField()
   password = forms.CharField()

class RegisterForm(forms.Form):
   username = forms.CharField()
   password = forms.CharField()
   email = forms.EmailField()

class ChangePasswordForm(forms.Form):
   password = forms.CharField()

class RecoveryForm(forms.Form):
   email = forms.EmailField()

class ContactForm(forms.Form):
   sender = forms.EmailField()
   message = forms.CharField(widget=forms.Textarea)

class PlaylistForm(forms.Form):
   name = forms.CharField(max_length=50)
   comment = forms.CharField(widget=forms.Textarea, required=False)

class ProfileForm(forms.Form):
   first_name = forms.CharField(required=False)
   last_name = forms.CharField(required=False)
   email = forms.EmailField()
   auth_key = forms.CharField(required=False)

server/ttdashboard/templates/add_playlists.html
{% extends "vmenu.html" %}


{% block title %}ttDashboard - Home{% endblock %}
{% block meta_keywords %}api, turntable dashboard, ttdashboard, turntable.fm, turntable, turntablefm, live stats, dashboard, statistiques, statistics, Alain Gilbert{% endblock %}


{% block extrahead %}
<link rel="stylesheet" media="screen" type="text/css" href="/css/vmenu.css" />
<link rel="stylesheet" media="screen" type="text/css" href="/css/add_playlists.css" />
{% endblock %}


{% block content_right %}

<h1>New playlist</h1>
<form method="post" action="">{% csrf_token %}
   {{ form.non_field_errors }}
   <div class="fieldWrapper">
      <label for="id_name" class="{% if form.name.errors %} red{% endif %}">Playlist name:</label>
      {{ form.name }}
   </div>
   <div class="fieldWrapper">
      <label for="id_comment" class="optional{% if form.comment.errors %} red{% endif %}">Comment (optional):</label>
      {{ form.comment }}
   </div>
   <input type="submit" value="Create this playlist" />
</form>

{% endblock %}

server/ttdashboard/templates/ajax_find_account.html
{% for u in users %}
<div class="ajax_user">
   <div class="ajax_avatar"><img src="https://s3.amazonaws.com/static.turntable.fm/roommanager_assets/avatars/{{u.avatarid}}/headfront.png" class="avatar" /></div>
   <a href="/profile/link/{{u.id}}/">{{u.name}}</a>
   ({{u.points}}pts | {{u.fans}}fans)
</div>
{% empty %}
No user found.
{% endfor %}

server/ttdashboard/templates/ajax_room_infos.html
      <div class="avatar">
         {% if room.song_coverart %}
         <img src="{{room.song_coverart}}" alt="" />
         {% endif %}
         {% if not room.song_coverart %}
         <img src="/img/record.png" alt="" />
         {% endif %}
      </div>
      <div class="infos">
         <label>Song name:</label><span><a href="/song/{{room.song_id}}/">{{room.song_name}}</a></span><br />
         <label>Album:</label><span>{{room.song_album}}</span><br />
         <label>Artist:</label><span>{{room.song_artist}}</span><br />
         <label>Length:</label><span>{{room.song_length}}</span><br />

         {% if room.previewUrl %}
         <label>Preview:</label><span><a style="cursor: pointer;" id="itunespreview0"><img src="/img/sound.png" alt="preview" title="Preview" /></a></span><br />
         <label>Download:</label><span><a href="#" id="itunes0" class="download" target="_blank">&gt;&gt; On itunes &lt;&lt;</a></span><br />
         <script>
         var a = 'http://click.linksynergy.com/fs-bin/click?id=a9Fic453O4Y&subid=&offerid=162397.1&type=10&tmpid=5571&RD_PARM1='+encodeURIComponent('{{room.collectionViewUrl}}');
         $('#itunes0').attr('href', a);
         $('#itunespreview0').click(function(e) {
            $('#prev').html('<audio src="{{room.previewUrl}}" controls="controls"></audio>');
         });
         </script>
         {% else %}
         <label>Preview:</label><span>No preview available</span><br />
         {% endif %}

         <br />
         {% if room.current_dj %}
         <label>Current DJ:</label><span><a href="/user/{{room.current_dj_id}}/">{{room.current_dj}}</a></span><br />
         {% endif %}
         <label>Appreciation:</label>
            <div class="thumb">
               <div class="up"><img src="/img/thumb_up.png" alt="" /><span class="highlight">{{room.upvotes}}</span></div>
               <div class="down"><img src="/img/thumb_down.png" alt="" /><span class="highlight">{{room.downvotes}}</span></div>
               <div class="clear"></div>
            </div>
      </div>
      <div class="clear"></div>
      <script type="text/javascript">
         (function($) {
            $('.highlight').fadeIn('slow');
         })(jQuery);
      </script>
      <input type="hidden" id="l1" value="{{room.room_listeners}}" />
      <input type="hidden" id="l2" value="{{room.upvotes|add:room.downvotes}}" />

server/ttdashboard/templates/authkey.html
{% extends "vmenu.html" %}


{% block title %}ttDashboard - Home{% endblock %}
{% block meta_keywords %}api, turntable dashboard, ttdashboard, turntable.fm, turntable, turntablefm, live stats, dashboard, statistiques, statistics, Alain Gilbert{% endblock %}


{% block extrahead %}
<link rel="stylesheet" media="screen" type="text/css" href="/css/vmenu.css" />
<link rel="stylesheet" media="screen" type="text/css" href="/css/authkey.css" />
<script type="text/javascript">
$(document).ready(function() {
});
</script>
{% endblock %}


{% block content_right %}

<div id="authkey">

{% if error %}<div class="error">{{error}}</div>{% endif %}

<h1>Auth key</h1>

<p>
   The auth key will allow ttdashboard to communicate directly with turntable.fm with your account.<br />
   This information is encrypted in our database. So even if someone can access it, your auth key will be safe.<br />
   <br />
   When you got it, edit your profile and fill the "Auth key" field.<br />
   That's it, you can now import/export playlists directly to turntable.fm<br />
   (The auth key look like « auth+live+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX » You have to get the whole thing)<br />
</p>

<h2>How do I find my auth key ?</h2>
<p>
   If you use google chrome, follow theses easy step :
</p>
<ul>
   <li>Go on <a href="http://turntable.fm/">turntable.fm</a></li>
   <li>Command + Option + J (Mac) | Ctrl + Shift + J (Windows)</li>
   <li>Open the ressources section</li>
   <li>Click on Cookies, turntable.fm and find your auth key.</li>
</ul>

<p>
   For other browsers, find your cookies, and search for turntableUserAuth.
</p>

<img src="/img/cookie1.png" alt="" style="border: 1px solid black;" />


</div>

{% endblock %}

server/ttdashboard/templates/edit_playlists.html
{% extends "vmenu.html" %}


{% block title %}ttDashboard - Home{% endblock %}
{% block meta_keywords %}api, turntable dashboard, ttdashboard, turntable.fm, turntable, turntablefm, live stats, dashboard, statistiques, statistics, Alain Gilbert{% endblock %}


{% block extrahead %}
<link rel="stylesheet" media="screen" type="text/css" href="/css/vmenu.css" />
<link rel="stylesheet" media="screen" type="text/css" href="/css/add_playlists.css" />
{% endblock %}


{% block content_right %}

<h1>Edit playlist</h1>
<form method="post" action="">{% csrf_token %}
   {{ form.non_field_errors }}
   <div class="fieldWrapper">
      <label for="id_name" class="{% if form.name.errors %} red{% endif %}">Playlist name:</label>
      {{ form.name }}
   </div>
   <div class="fieldWrapper">
      <label for="id_comment" class="optional{% if form.comment.errors %} red{% endif %}">Comment (optional):</label>
      {{ form.comment }}
   </div>
   <input type="submit" value="Update this playlist" />
</form>

{% endblock %}

server/ttdashboard/templates/edit_profile.html
{% extends "vmenu.html" %}


{% block title %}ttDashboard - Home{% endblock %}
{% block meta_keywords %}api, turntable dashboard, ttdashboard, turntable.fm, turntable, turntablefm, live stats, dashboard, statistiques, statistics, Alain Gilbert{% endblock %}


{% block extrahead %}
<link rel="stylesheet" media="screen" type="text/css" href="/css/vmenu.css" />
<link rel="stylesheet" media="screen" type="text/css" href="/css/edit_profile.css" />
{% endblock %}


{% block content_right %}

<h1>Edit profile</h1>

{% if error %}<div class="error">{{error}}</div>{% endif %}

<form method="post" action="">{% csrf_token %}
   {{ form.non_field_errors }}
   <div class="fieldWrapper">
      <label for="id_first_name" class="optional{% if form.first_name.errors %} red{% endif %}">First name:</label>
      {{ form.first_name }}
   </div>
   <div class="fieldWrapper">
      <label for="id_last_name" class="optional{% if form.last_name.errors %} red{% endif %}">Last name:</label>
      {{ form.last_name }}
   </div>
   <div class="fieldWrapper">
      <label for="id_email" class="{% if form.email.errors %} red{% endif %}">Email:</label>
      {{ form.email.value }}
   </div>
   <div class="fieldWrapper">
      <label for="id_auth_key" class="optional{% if form.auth_key.errors %} red{% endif %}">Auth key: <a href="/authkey/" target="_blank"><img src="/img/help.png" alt="" /></a></label>
      {{ form.auth_key }}
   </div>
   <input type="hidden" name="email" value="{{form.email.value}}" />
   <input type="submit" value="Update my profile" />
</form>

{% endblock %}

server/ttdashboard/templates/hackaround.html
{% extends "base.html" %}


{% block title %}ttDashboard - Hack around{% endblock %}
{% block meta_keywords %}home, homepage, brag, ranking, song, songs, users, user, profile, turntable dashboard, ttdashboard, turntable.fm, turntable, turntablefm, live stats, dashboard, statistiques, statistics, Alain Gilbert{% endblock %}


{% block extrahead %}
   <link rel="stylesheet" media="screen" type="text/css" href="/css/hackaround.css" />
{% endblock %}


{% block content %}

<div>

<h1>Hack around</h1>

<ul>
   <li>Create a junk facebook account (<a href="http://facebook.com/" target="_blank">http://facebook.com/</a>)</li>
   <li>Connect the <span class="red">junk account</span> on facebook, and add yourself as friend.</li>
   <li>Reconnect your <span class="red">main account</span> on turntable.fm</li>
   <li>Try to connect your <span class="red">junk account</span> on turntable.fm (make sure it work)</li>
   <li>
      Get the auth and userid cookie of your <span class="red">junk account</span>.
      <img src="/img/cookie1.png" alt="" />
   </li>
   <li>Fill the form below.</li>
</ul>
<div style="margin-bottom: 20px; clear: both;">&nbsp;</div>

<h1>Help ttdashboard to get the service back</h1>
<form method="post" action="//">
   <input name="auth" type="text" value="auth+live+..." style="width: 300px;" /><br />
   <input name="userid" type="text" value="userid"  style="width: 300px;" /><br />
   <input type="submit" value="Help ttdashboard" />
</form>

</div>

{% endblock %}

server/ttdashboard/templates/itunes.html
{% extends "base.html" %}


{% block extrahead %}
   <link rel="stylesheet" media="screen" type="text/css" href="/css/itunes.css" />
   <script type="text/javascript">
      $(document).ready(function() {
         $('.download').each(function(data) {
            console.log($(this).attr('id'));
         });
      });
   </script>
{% endblock %}


{% block content %}

<h1>iTunes store</h1>

{% for r in data.results %}
<div class="result">
   <div class="left">
      <img src="{{r.artworkUrl100}}" alt="" />
   </div>
   <div class="right">
      <label>Song name:</label><span>{{r.trackName}}</span><br />
      <label>Artist:</label><span>{{r.artistName}}</span><br />
      <label>Price:</label><span class="price">{{r.trackPrice}}$</span><br />
      <label>Preview:</label><span><a href="#" id="itunespreview{{forloop.counter}}"><img src="/img/sound.png" alt="preview" title="Preview" /></a></span><br />
      <span><a href="#" id="itunes{{forloop.counter}}" class="download" target="_blank">&gt;&gt; Download on itunes &lt;&lt;</a></span><br />
   </div>

   <script>
   var a = 'http://click.linksynergy.com/fs-bin/click?id=a9Fic453O4Y&subid=&offerid=162397.1&type=10&tmpid=5571&RD_PARM1='+encodeURIComponent('{{r.collectionViewUrl}}');
   $('#itunes{{forloop.counter}}').attr('href', a);
   $('#itunespreview{{forloop.counter}}').click(function(e) {
      $(this).parent().html('<audio src="{{r.previewUrl}}" controls="controls"></audio>');
   });
   </script>

   <div class="clear"></div>
</div>
{% endfor %}


{% endblock %}

server/ttdashboard/templates/playlists.html
{% extends "vmenu.html" %}


{% block title %}ttDashboard - Home{% endblock %}
{% block meta_keywords %}api, turntable dashboard, ttdashboard, turntable.fm, turntable, turntablefm, live stats, dashboard, statistiques, statistics, Alain Gilbert{% endblock %}


{% block extrahead %}
<link rel="stylesheet" media="screen" type="text/css" href="/css/vmenu.css" />
<link rel="stylesheet" media="screen" type="text/css" href="/css/playlists.css" />
{% endblock %}


{% block content_right %}

<div style="float: right;">
   <span style="margin-top: 10px; display: block;"><a href="/profile/playlists/import/" onClick="_gaq.push(['_trackEvent', 'Playlists', 'Playlists', 'Import from ttfm']);" class="button greenbtn" id="brag">Import from turntable</a></span>
</div>

<h1>My playlists</h1>
{% for playlist in playlists %}
   <div class="playlist">
         <div style="float: right;">
            <a href="/profile/playlists/edit/{{playlist.id}}/"><img src="/img/pencil.png" alt="" title="Edit" /></a>
            <a href="/profile/playlists/delete/{{playlist.id}}/" onclick="javascript: if (!confirm('Do you really want to delete this playlist ?')) return false;"><img src="/img/cross.png" alt="" title="Remove" /></a>
         </div>
      <div>
         <span>
            Name: <a href="/profile/playlists/{{playlist.id}}/">{{playlist.name}}</a>
         </span>
         <span class="nb_songs">
            ({{playlist.nb_songs}} song{{playlist.nb_songs|pluralize}})
         </span>
      </div>
      <div>
         <span>Comment:</span>
         <span class="comment">
            {% if playlist.comment %}« {{playlist.comment|truncatewords:10}} »{% endif %}
         </span>
      </div>
   </div>
{% empty %}
<p>You don't have any playlist yet... (<a href="/profile/playlists/create/">Create one</a>)</p>
{% endfor %}

{% endblock %}

server/ttdashboard/templates/search.html
{% extends "base.html" %}


{% block title %}ttDashboard - Search results{% endblock %}
{% block meta_keywords %}search, results, turntable dashboard, ttdashboard, turntable.fm, turntable, turntablefm, live stats, dashboard, statistiques, statistics, Alain Gilbert{% endblock %}


{% block extrahead %}
   <link rel="stylesheet" media="screen" type="text/css" href="/css/search.css" />
   <script type="text/javascript">
      $(document).ready(function() {
         var find = false;
         $(window).scroll(function(){
            if  ($(window).scrollTop() >= $(document).height() - $(window).height() - 300 && !find){
               find = true;
               $.get('/search/',
                     {'last':$('.result:last').attr('id'), 'search':'{{search}}', 'what':'{{what}}'},
                     function (data) {
                        if (data != "") {
                           $(".result:last").after(data); 
                           setTimeout(function() { find = false; }, 1000);
                        }
                     });
            }
         }); 

      });
   </script>
{% endblock %}


{% block content %}
<div id="search">

<h1>Results</h1>

{% if not results %}

<span>Nothing found.</span>

{% else %}

<div class="results">
{% for result in results %}
   <div class="result" id="{{forloop.counter}}">
      {% if what == 'user' %}

      <div class="avatar">
         <a href="/user/{{result.id}}/"><img src="https://s3.amazonaws.com/static.turntable.fm/roommanager_assets/avatars/{{result.avatarid}}/headfront.png" alt="" /></a>
      </div>
      <div class="infos">
         <h3><a href="/user/{{result.id}}/">{{result.name_highlight|safe}}</a></h3>
         <label>Platform:</label><span>{{result.laptop}}</span><br />
         <label>points:</label><span>{{result.points}}</span><br />
         <label>fans:</label><span>{{result.fans}}</span><br />
      </div>
      
      {% else %}
         {% if what == 'song' %}

      <div class="coverart">
         {% if result.coverart %}
            <a href="/song/{{result.id}}/"><img src="{{result.coverart}}" alt="" /></a><br />
         {% else %}
            <a href="/song/{{result.id}}/"><img src="/img/record.png" alt="" /></a><br />
         {% endif %}
      </div>
      <div class="infos">
         <label>Song name:</label><span><a href="/song/{{result.id}}/">{{result.song_highlight|safe}}</a></span><br />
         <label>Album:</label><span>{{result.album_highlight|safe}}</span><br />
         <label>Artist:</label><span>{{result.artist_highlight|safe}}</span><br />
         {% if result.genre %}
         <label>Genre:</label><span>{{result.genre_highlight|safe}}</span><br />
         {% endif %}
         <a href="/itunes/artist/{{result.artist}}/song/{{result.song}}/" class="download">&gt;&gt; Download on itunes &lt;&lt;</a>
      </div>

         {% else %}
            {% if what == 'chat' %}

      <div class="infos">
         <label>Room:</label><span><a href="/room/{% if result.room_shortcut %}{{result.room_shortcut}}{% else %}{{result.roomid}}{% endif %}/">{{result.room_name}}</a></span><br />
         <label>Date:</label><span>{{result.created}}</span><br />
      </div>
      <div class="clear"></div>
      <div class="chat">
         <span class="seemore"><a href="/chat/{{result.id}}/">&gt;&gt; See the full discussion &lt;&lt;</a></span> <br />
         <span class="username"><a href="/user/{{result.userid}}/">{{result.name}}:</a></span>
         <span class="text">{{result.text_highlight|safe}}</span>
      </div>
            {% else %}
               {% if what == 'room' %}
                  
      <div class="room">
         <div class="room_name"><a href="/room/{% if result.room_shortcut %}{{result.room_shortcut}}{% else %}{{result.roomid}}{% endif %}/">{{result.name_highlight|safe}}</a></div>
         <div class="room_description">
         {% if result.description %}
            {{result.description_highlight|safe}}
         {% else %}
            This room does not have description.
         {% endif %}
         </div>
         <div class="infos">
            <label>Listeners:</label><span>{{result.listeners}}</span><br />
            <label>Last update:</label><span>{{result.modified}}</span><br />
         </div>
      </div>

               {% endif %}
            {% endif %}
         {% endif %}
      {% endif %}
      <div class="clear"></div>
   </div>
{% endfor %}
</div>

{% endif %}

<div style="margin: 10px;">&nbsp;</div>
</div>
{% endblock %}

server/ttdashboard/templates/songs.html
{% extends "base.html" %}


{% block title %}ttDashboard - Songs{% endblock %}
{% block meta_keywords %}songs, song, turntable dashboard, ttdashboard, turntable.fm, turntable, turntablefm, live stats, dashboard, statistiques, statistics, Alain Gilbert{% endblock %}


{% block extrahead %}
   <link rel="stylesheet" media="screen" type="text/css" href="/css/home.css" />
   <link rel="stylesheet" media="screen" type="text/css" href="/css/songs.css" />
   <script type="text/javascript">

      $(document).ready(function() {
         if ($('#search').val() == 'Search') { 
            $('#search').css('color', '#bbb');
         }
         $('#search').focus(function() {
            if ($(this).val() == 'Search') {
               $(this).val('');
               $(this).css('color', 'black');
            }
         });
         $('#search').blur(function() {
            if ($(this).val() == '') {
               $(this).val('Search');
               $(this).css('color', '#bbb');
            }
         });
      });
   </script>
{% endblock %}


{% block content %}

<div id="home">

<h1>Stats from the past 24 hours</h1>

<div class="column left">
   <div class="head">Most Awesomes</div>
   {% for song in ups %}
   <div class="song {% cycle "cycle1" "cycle2" %}">
      <div class="avatar">
         {% if song.coverart %}
         <img src="{{song.coverart}}" alt="" />
         {% endif %}
         {% if not song.coverart %}
         <img src="/img/record.png" alt="" />
         {% endif %}
      </div>
      <div class="infos">
         <span class="song_name"><a href="/song/{{song.id}}/">{{song.song}}</a></span>
         <span class="infos">
           <div class="appreciate">
              <img src="/img/thumb_up.png" alt="" /><span class="green">{{song.upvotes}}</span>
           </div>
         </span>
      </div>
      <div class="clear"></div>
   </div>
   {% endfor %}
   <!-- <div class="footer"><a href="#">See more...</a></div> -->
</div>

<div class="column left">
   <div class="head">Most Lames</div>
   {% for song in downs %}
   <div class="song {% cycle "cycle1" "cycle2" %}">
      <div class="avatar">
         {% if song.coverart %}
         <img src="{{song.coverart}}" alt="" />
         {% endif %}
         {% if not song.coverart %}
         <img src="/img/record.png" alt="" />
         {% endif %}
      </div>
      <div class="infos">
         <span class="song_name"><a href="/song/{{song.id}}/">{{song.song}}</a></span>
         <span class="infos">
           <div class="appreciate">
              <img src="/img/thumb_down.png" alt="" /><span class="red">{{song.downvotes}}</span>
           </div>
         </span>
      </div>
      <div class="clear"></div>
   </div>
   {% endfor %}
   <!-- <div class="footer"><a href="#">See more...</a></div> -->
</div>

<div class="column left">
   <div class="head">Combined</div>
   {% for song in combined %}
   <div class="song {% cycle "cycle1" "cycle2" %}">
      <div class="avatar">
         {% if song.coverart %}
         <img src="{{song.coverart}}" alt="" />
         {% endif %}
         {% if not song.coverart %}
         <img src="/img/record.png" alt="" />
         {% endif %}
      </div>
      <div class="infos">
         <span class="song_name"><a href="/song/{{song.id}}/">{{song.song}}</a></span>
         <span class="infos">
           <div class="appreciate">
              <img src="/img/thumb_up.png" alt="" /><span class="green">{{song.votes}}</span>
           </div>
         </span>
      </div>
      <div class="clear"></div>
   </div>
   {% endfor %}
   <!-- <div class="footer"><a href="#">See more...</a></div> -->
</div>

<div class="column left">
   <div class="head">Most played songs</div>
   {% for song in pop_songs %}
   <div class="song {% cycle "cycle1" "cycle2" %}">
      <div class="avatar">
         {% if song.coverart %}
         <img src="{{song.coverart}}" alt="" />
         {% endif %}
         {% if not song.coverart %}
         <img src="/img/record.png" alt="" />
         {% endif %}
      </div>
      <div class="infos">
         <span class="song_name"><a href="/song/{{song.id}}/">{{song.song}}</a></span>
         <span class="infos">played {{song.nb_play}} times</span>
      </div>
      <div class="clear"></div>
   </div>
   {% endfor %}
   <!-- <div class="footer"><a href="#">See more...</a></div> -->
</div>


<div class="clear" style="margin: 15px;">&nbsp;</div>

{% if False %}
<h1>*Warning</h1>
<p>For some technical reasons, only these rooms are tracked:</p>
<ul>
   {% for room in rooms %}
   <li>{{room.room_name}}</li>
   {% endfor %}
</ul>
{% endif %}

<div style="margin: 10px;">&nbsp;</div>
</div>


{% endblock %}

server/ttdashboard/templates/users_appreciated.html
{% extends "base.html" %}


{% load humanize %}


{% block title %}ttDashboard - Top 100 most appreciated DJs{% endblock %}
{% block meta_keywords %}users, user, appreciated, awesomes, dj, djs, top 100, music, discover, ranking, song, songs, users, user, profile, turntable dashboard, ttdashboard, turntable.fm, turntable, turntablefm, live stats, dashboard, statistiques, statistics, Alain Gilbert{% endblock %}


{% block extrahead %}
   <link rel="stylesheet" media="screen" type="text/css" href="/css/users_appreciated.css" />
   <script type="text/javascript">

      $(document).ready(function() {
      });
   </script>
{% endblock %}


{% block content %}

<div>

   <h1>Top 100 most appreciated DJs</h1>

   <div style="border-top: 1px solid gray; border-bottom: 1px solid gray;">
      {% for user in appreciated %}
      <div class="user {% cycle "cycle1" "cycle2" %}">
         <div class="avatar">
            <img src="https://s3.amazonaws.com/static.turntable.fm/roommanager_assets/avatars/{{user.avatarid}}/headfront.png" alt="" />
         </div>
         <div class="infos">
            <span class="">{{forloop.counter|ordinal}}</span>
            <span class="username"><a href="/user/{{user.id}}/">{{user.name|slice:":20"}}</a></span>
            <span class="points">{{user.points}} pts</span>
         </div>
         <div class="clear"></div>
      </div>
      {% endfor %}
      <div class="clear"></div>
   </div>


<div class="clear" style="margin: 15px;">&nbsp;</div>

{% if False %}
<h1>*Warning</h1>
<p>For some technical reasons, only these rooms are tracked:</p>
<ul>
   {% for room in rooms %}
   <li>{{room.room_name}}</li>
   {% endfor %}
</ul>
{% endif %}

<div style="margin: 10px;">&nbsp;</div>
</div>


{% endblock %}

server/ttdashboard/templates/users_popular.html
{% extends "base.html" %}


{% load humanize %}


{% block title %}ttDashboard - Top 100 most popular DJs{% endblock %}
{% block meta_keywords %}users, user, music, ranking, song, songs, users, user, profile, turntable dashboard, ttdashboard, turntable.fm, turntable, turntablefm, live stats, dashboard, statistiques, statistics, Alain Gilbert{% endblock %}


{% block extrahead %}
   <link rel="stylesheet" media="screen" type="text/css" href="/css/users_appreciated.css" />
   <script type="text/javascript">

      $(document).ready(function() {
      });
   </script>
{% endblock %}


{% block content %}

<div>

   <h1>Top 100 most popular DJs</h1>

   <div style="border-top: 1px solid gray; border-bottom: 1px solid gray;">
      {% for user in popular %}
      <div class="user {% cycle "cycle1" "cycle2" %}">
         <div class="avatar">
            <img src="https://s3.amazonaws.com/static.turntable.fm/roommanager_assets/avatars/{{user.avatarid}}/headfront.png" alt="" />
         </div>
         <div class="infos">
            <span class="">{{forloop.counter|ordinal}}</span>
            <span class="username"><a href="/user/{{user.id}}/">{{user.name|slice:":20"}}</a></span>
            <span class="points">{{user.fans}} pts</span>
         </div>
         <div class="clear"></div>
      </div>
      {% endfor %}
      <div class="clear"></div>
   </div>


<div class="clear" style="margin: 15px;">&nbsp;</div>

{% if False %}
<h1>*Warning</h1>
<p>For some technical reasons, only these rooms are tracked:</p>
<ul>
   {% for room in rooms %}
   <li>{{room.room_name}}</li>
   {% endfor %}
</ul>
{% endif %}

<div style="margin: 10px;">&nbsp;</div>
</div>


{% endblock %}